/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Dialog;

import BackEnd.EventSystem.Task;
import GUI.DesignDefault;
import GUI.TaskPanel;
import auth.AuthorizationException;

import javax.swing.JOptionPane;

/**
 *
 * @author Sid
 */
public class TaskDialog extends javax.swing.JDialog {
    
    /**
     * Creates new form TaskDialog
     */
    private boolean confirm;
    private TaskPanel taskPanel;
    private DesignDefault dd;
    
    public TaskDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        dd = DesignDefault.getInstance();
        initComponents();
        taskPanel = new TaskPanel();
        taskPanelHolder.add(taskPanel);
        taskPanel.setVisible(true);
        taskPanel.setSize(430,329);
        confirm = false;
        /* Added following line to center dialog. -Ketty */
        setLocationRelativeTo(null);
        this.setBackground(dd.getBGColor());
        this.setTitle("Edit Task");
    }
   
    public boolean getConfirm()
    { return confirm; }
    
    public Task createTask()
        throws AuthorizationException{
        return taskPanel.createTask();
    }
    
    public void setToViewOnly() {
        taskPanel.setToViewOnly();
        saveButton.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        taskPanelHolder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        saveButton.setFont(dd.getStandardText());
        saveButton.setMinimumSize(dd.getBigButtonDimension());
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                try{
                    saveButtonActionPerformed(evt);
                }catch( AuthorizationException ignored){}
            }
        });

        closeButton.setFont(dd.getStandardText());
        closeButton.setMinimumSize(dd.getBigButtonDimension());
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        taskPanelHolder.setPreferredSize(new java.awt.Dimension(450, 330));

        javax.swing.GroupLayout taskPanelHolderLayout = new javax.swing.GroupLayout(taskPanelHolder);
        taskPanelHolder.setLayout(taskPanelHolderLayout);
        taskPanelHolderLayout.setHorizontalGroup(
            taskPanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        taskPanelHolderLayout.setVerticalGroup(
            taskPanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(taskPanelHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(taskPanelHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)
            throws AuthorizationException{//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Task t = createTask();
        if(t.getTitle().trim().length() == 0 || t.getTitle().trim().equals("(none)"))
        {
            JOptionPane.showMessageDialog(null, "Task name can not be blank, please provide a valid name.", "No Task Name", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            confirm = true;
            this.dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialog dialog = new TaskDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel taskPanelHolder;
    // End of variables declaration//GEN-END:variables
}
