/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackEnd.EventSystem.Budget;
import BackEnd.EventSystem.Committee;
import BackEnd.EventSystem.Expense;
import BackEnd.ManagerSystem.MainManager;
import BackEnd.ManagerSystem.ManagerExceptions.PrivilegeInsufficientException;
import EMS_Database.DoesNotExistException;
import EMS_Database.DuplicateInsertionException;
import GUI.Dialog.NewExpenseDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.DataBindingException;

import auth.AuthorizationException;
import exception.UpdateException;

/**
 *
 * @author sara
 */
public class CommitteeBudgetExpense extends javax.swing.JPanel {

    /**
     * Creates new form Expenses
     */
    private MainManager manager;
    private Budget selectedBudget;
    
    public CommitteeBudgetExpense() throws AuthorizationException{
        manager = MainManager.getInstance();
        selectedBudget = manager.getBudgetManager().getSelectedBudget();
        initComponents();
        updateInfo();
    }
    
    public void updateInfo() throws AuthorizationException
    {
        DefaultTableModel model = getTableModel();
        model.setRowCount(0);
        if(manager.getCommitteeManager().getSelectedCommittee() != null)
        {
            Committee c = manager.getCommitteeManager().getSelectedCommittee();
            for(Expense e : c.getBudget().getExpenseList())
            {
                model.addRow(
                    new Object[]
                    {
                        e.getBUDGET_ITEM_ID(),e.getDescription(),e.getValue()
                    });
            }
        }
        expenseTotalLabel.setText("Total : $" + String.format("%,.2f", selectedBudget.getTotalExpense()));
    }
    
    public DefaultTableModel getTableModel(){ 
        return (DefaultTableModel)expensesTable.getModel(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws AuthorizationException{

        expensesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expensesTable = new javax.swing.JTable();
        addExpenseButton = new javax.swing.JButton();
        deleteExpenseButton = new javax.swing.JButton();
        expenseTotalLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(395, 500));

        expensesLabel.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        expensesLabel.setText("Expenses");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 500));

        expensesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Description", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        expensesTable.setPreferredSize(new java.awt.Dimension(384, 407));
        expensesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(expensesTable);
        expensesTable.getColumnModel().getColumn(0).setResizable(false);
        expensesTable.getColumnModel().getColumn(0).setPreferredWidth(15);
        expensesTable.getColumnModel().getColumn(1).setResizable(false);
        expensesTable.getColumnModel().getColumn(2).setResizable(false);
        expensesTable.getColumnModel().getColumn(2).setPreferredWidth(30);

        addExpenseButton.setText("Add Expense");
        addExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                try{
                    addExpenseButtonActionPerformed(evt);
                }catch (AuthorizationException ignore ){}
            }
        });

        deleteExpenseButton.setText("Delete Expense");
        deleteExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try{
                    deleteExpenseButtonActionPerformed(evt);
                }catch (AuthorizationException ignore ){}
            }
        });

        expenseTotalLabel.setText("Total : $" + selectedBudget.getTotalExpense());
        expenseTotalLabel.setMaximumSize(new java.awt.Dimension(275, 15));
        expenseTotalLabel.setMinimumSize(new java.awt.Dimension(275, 15));
        expenseTotalLabel.setPreferredSize(new java.awt.Dimension(275, 15));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(deleteExpenseButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addExpenseButton))
                    .add(layout.createSequentialGroup()
                        .add(expensesLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(expenseTotalLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(expensesLabel)
                    .add(expenseTotalLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addExpenseButton)
                    .add(deleteExpenseButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addExpenseButtonActionPerformed(java.awt.event.ActionEvent evt)
        throws AuthorizationException{//GEN-FIRST:event_addExpenseButtonActionPerformed
        NewExpenseDialog ned = new NewExpenseDialog(null, true);
        ned.setVisible(true);
        if(ned.getConfirm())
        {
            try
            {
                Expense e = ned.createExpense();
                manager.getBudgetManager().createExpense(e);
            }
            catch (UpdateException error)
            {
                JOptionPane.showMessageDialog(this, "Cannot add this entry.");
                System.out.println("Expense update error in Committee Expense: " + error.getMessage());
            }catch (PrivilegeInsufficientException ex){
            }catch (DoesNotExistException dataEx){
            }catch (DuplicateInsertionException dupEx){}
        }
        updateInfo();
    }//GEN-LAST:event_addExpenseButtonActionPerformed

    private void deleteExpenseButtonActionPerformed(java.awt.event.ActionEvent evt)
        throws AuthorizationException{//GEN-FIRST:event_deleteExpenseButtonActionPerformed
        int selection = expensesTable.getSelectedRow();
        
        if(selection < 0){
            JOptionPane.showMessageDialog(
                    null, "Please select an expense to delete.", "No Expense Selected", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Expense expense = manager.getCommitteeManager().getSelectedCommittee().getBudget().getExpenseList().get(selection);
            
            try {
                manager.getBudgetManager().deleteExpense(expense);
            }
            catch(UpdateException error) {
                JOptionPane.showMessageDialog(this, "Unable to delete.");
                System.out.println("Deletion error in Committee Expense: " + error.getMessage());
            }catch (AuthorizationException ex){
            }catch (PrivilegeInsufficientException pEx){
            }catch (DoesNotExistException DNEex){}

            updateInfo();
        }
    }//GEN-LAST:event_deleteExpenseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JButton deleteExpenseButton;
    private javax.swing.JLabel expenseTotalLabel;
    private javax.swing.JLabel expensesLabel;
    private javax.swing.JTable expensesTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}