/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackEnd.ManagerSystem.MainManager;
import GUI.Dialog.EditEventDialog;
import auth.AuthorizationException;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Karina
 */
public class EventDetailsPanel extends javax.swing.JPanel {

    private MainManager manager;
    /**
     * Creates new form EventDetailsPanel
     */
    public EventDetailsPanel() throws AuthorizationException{
        initComponents();
        manager = MainManager.getInstance();
        updateLabels();
    }
    
    /**
     * Updates the labels to the relevant information for the event
     */
    public void updateLabels() throws AuthorizationException
    {
        eventNameLabel.setText(manager.getEventManager().getSelectedEvent().getTitle());
        descriptionTextArea.setText(manager.getEventManager().getSelectedEvent().getDescription());
        locationArea.setText(manager.getEventManager().getSelectedEvent().getLocation().toString());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventNameLabel = new javax.swing.JLabel();
        mainEventLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        locationLabel = new javax.swing.JLabel();
        locationArea = new javax.swing.JLabel();
        editEventButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(128, 128, 128));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));

        eventNameLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        eventNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        eventNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventNameLabel.setText("Name of Event");

        mainEventLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mainEventLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainEventLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainEventLabel.setText("Main Event:");

        descriptionLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setText("Description:");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setBackground(new java.awt.Color(204, 204, 204));
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        locationLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        locationLabel.setForeground(new java.awt.Color(255, 255, 255));
        locationLabel.setText("Location:");

        locationArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        locationArea.setForeground(new java.awt.Color(255, 255, 255));
        locationArea.setText("The location of this event");

        editEventButton.setText("Edit this Event");
        editEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEventButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainEventLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(locationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(locationArea, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editEventButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainEventLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventNameLabel)
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(locationArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(editEventButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Edits the main event using a dialog
     */
    private void editEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEventButtonActionPerformed
        EditEventDialog eed = new EditEventDialog((JFrame) SwingUtilities.windowForComponent(this), true);
        eed.setVisible(true);
        if (eed.getConfirm()) {
            try {
                updateLabels();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_editEventButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton editEventButton;
    private javax.swing.JLabel eventNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationArea;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel mainEventLabel;
    // End of variables declaration//GEN-END:variables
}
