/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BackEnd.EventSystem.Committee;
import BackEnd.EventSystem.Expense;
import BackEnd.EventSystem.Income;
import BackEnd.ManagerSystem.MainManager;
import GUI.Dialog.NewIncomeDialog;
import auth.AuthorizationException;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sara
 */
public class TotalBudgetIncome extends javax.swing.JPanel {

    /**
     * Creates new form BudgetIncome
     */
    
    private MainManager manager;
    
    public TotalBudgetIncome() throws AuthorizationException{
        initComponents();
        manager = MainManager.getInstance();
        updateInfo();
    }
    
    public void updateInfo()
        throws AuthorizationException{
        DefaultTableModel model = getTableModel();
        model.setRowCount(0);
        
        if(manager.getEventManager().getSelectedEvent().getCommitteeList() != null)
        {
        for(Committee c : manager.getEventManager().getSelectedEvent().getCommitteeList()){
            Income i = new Income();
            i.setDescription(c.getTitle());
            i.setValue(c.getBudget().getTotalIncome());
            {
                model.addRow(
                    new Object[]
                    {
                        c.getTitle(),"Total Incomes",i.getValue()
                    });
            }
        }
        } 
    }
    
    public DefaultTableModel getTableModel()
    { return (DefaultTableModel)incomeTable.getModel(); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        incomeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        incomeTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(370, 600));

        incomeLabel.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        incomeLabel.setText("Income");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 500));

        incomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "no",  new Double(201.0)}
            },
            new String [] {
                "Item ID", "Description", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        incomeTable.setPreferredSize(new java.awt.Dimension(384, 407));
        incomeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(incomeTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(incomeLabel)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(incomeLabel)
                .add(12, 12, 12)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 530, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JTable incomeTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
